export const API_BASE_URL = "http://localhost:8000"

export const SONG_TITLE_MAPPING = {
  "s001": "Roundtable Rival (clip)",
  "s002": "Myosotis (clip)",
  "s003": "stop it (clip)",
  "s004": "Beneath the Mask (clip)",
  "s005": "i wish you would come closer and hold me (clip)",
  "s006_1": "Water Flower p.1 (clip)",
  "s006_2": "Water Flower p.2 (clip)",
  "s006_3": "Water Flower p.3 (clip)",
  "s007": "Danse Macabre (clip)",
  "s008": "Theme of Violet Evergarden (clip)",
  "s009": "Ashes of Dreams (clip)",
  "s010_1": "Stars and Stripes Forever p.1 (clip)",
  "s010_2": "Stars and Stripes Forever p.2 (clip)",
  "s011": "Dark Academia (clip)",
  "s012": "Ballade No. 1 in G minor, Op. 23 (clip)",
  "s013": "The Phantom of the Opera (clip)",
  "s014_1": "Beethoven's 5 Secrets p.1 (clip)",
  "s014_2": "Beethoven's 5 Secrets p.2 (clip)",
  "s015": "Arabesque No. 1 (clip)",
  "s016": "A Stormy Night (clip)",
  "s017": "葬花 (clip)",
  "s018": "Echo (clip)",
  "s019": "Spider Dance (clip)",
  "s020": "Unity (clip)",
  "s021_1": "God of the Dead p.1 (clip)",
  "s021_2": "God of the Dead p.2 (clip)",
  "s021_3": "God of the Dead p.3 (clip)",
  "s022": "Purple Hyacinth Theme (clip)",
  "s023": "四月 (Shigatsu) (clip)",
  "s024": "Max & Chloe (clip)",
  "s025": "Shrine Battle (The Legend of Zelda: Breath of the Wild OST) (clip)",
  "s026": "Carmen (Guitar) (clip)",
  "s027": "Evangeline (clip)",
  "s028": "If We Have Each Other (clip)",
  "s029": "Feed the Machine (clip)",
  "s030": "HOPE (clip)",
  "s031": "Angel Tango (clip)",
  "s032": "Curses (clip)",
  "s033": "Paint It, Black (clip)",
  "s034": "Come Here (clip)",
  "s035": "A Rock Somewhere (clip)",
  "s036": "Runaway (clip)",
  "s037": "Fight for Me (clip)",
  "s038": "Playground (clip)",
  "s039": "More Than My Hometown (Audio Only) (clip)",
  "s040": "wednesday (clip)",
  "s041": "The Upside (clip)",
  "s042": "Space Ghost Coast To Coast (clip)",
  "s043": "Close To The Sun (clip)",
  "s044": "Shivers (clip)",
  "s045": "Love Me Like You Do (clip)",
  "s046": "A Night To Remember (clip)",
  "s047": "Mood (clip)",
  "s048": "Amelie Farren (clip)",
  "s049": "friendly fire (clip)",
  "s050": "642 Ways | Seycara (clip)",
  "s051": "Toast (clip)",
  "s052": "Into The Night (English Ver.) (clip)",
  "s053": "It May Sound Strange (clip)",
  "s054": "Entre deux (clip)",
  "s055": "femmes (clip)",
  "s056": "Comme Un Bateau (clip)",
  "s057": "1,2,3 (clip)",
  "s058": "Tous les Mêmes (Stromae Cover) (clip)",
  "s059": "Tous les Mêmes (clip)",
  "s060": "Arbre (clip)",
  "s061": "Canopée (audio) (clip)",
  "s062": "Compliqué (clip)",
  "s063": "TWENNY TWENNY (clip)",
  "s064_1": "Aishite Aishite Aishite p.1 (clip)",
  "s064_2": "Aishite Aishite Aishite p.2 (clip)",
  "s065": "Love decorate (恋愛デコレート) (clip)",
  "s066": "Yoru ni Kakeru (夜に駆ける) (clip)",
  "s067": "Be a flower (花になって) (clip)",
  "s068": "Bamboo Disco (バンブーディスコ) (clip)",
  "s069": "Stay with me (真夜中のドア) (clip)",
  "s070_1": "INSOMNIA (インソムニア) p.1 (clip)",
  "s070_2": "INSOMNIA (インソムニア) p.2 (clip)",
  "s071": "Requiem (レクイエム) (clip)",
  "s072": "Koe (声) (clip)",
  "s073": "Spring Thief (春泥棒) (clip)",
  "s074": "tape/stop/night (clip)",
  "s075": "Maple Wind (clip)",
  "s076": "Ring Ring Ring (clip)",
  "s077": "熱愛105°C的你 (clip)",
  "s078": "大理寺日志 (clip)",
  "s079": "Upwards to the Moon (左手指月) (clip)",
  "s080": "要不然我们就这样一万年 (clip)",
  "s081": "Qué vendrá (clip)",
  "s082": "FORTUNA (clip)",
  "s083": "Fukurou (German version) (clip)",
  "s084": "Мой мармеладный (clip)",
  "s085": "Itoki Hana (糸奇はな) (clip)",
  "s086": "Fever (clip)",
  "s087": "Amusement Park Theme (clip)",
  "s088": "SUPADOPA (clip)",
  "s089": "Pasensya Ka Na (clip)",
  "s090_1": "Come Play p.1 (clip)",
  "s090_2": "Come Play p.2 (clip)",
  "s091": "Khayal (خيال) (clip)",
  "s092": "Téir Abhaile Riú (clip)",
  "s093": "Hawaiian Roller Coaster Ride (clip)",
  "s094": "Altay (clip)",
  "s095": "Malhari (clip)",
  "s096": "Saraiman (clip)",
  "s097": "Time to Say Goodbye (clip)",
  "s098": "Cara Mia Addio (clip)",
  "s099": "The Passing of the Elves (clip)",
  "s100": "Mұны неге білмейсің? (clip)"
}
